@startuml
class com.ronelgazar.touchtunes.activity.LoginActivity {
- ActivityResultLauncher<Intent> signInLauncher
- List<AuthUI.IdpConfig> providers
- Intent signInIntent
- FirebaseUser user
- FirebaseFirestore db
# void onCreate(Bundle)
- void onSignInResult(FirebaseAuthUIAuthenticationResult)
- void fetchModeAndPlaylist(Map<String,Object>,DocumentReference,DocumentReference,PatientCallback)
- void showToast(String)
- void savePatientToSharedPrefs(Patient)
}


interface com.ronelgazar.touchtunes.activity.LoginActivity$PatientCallback {
~ void onPatientDataLoaded(Patient)
}

class com.ronelgazar.touchtunes.util.DefualtData {
+ {static} Playlist getDefaultPlaylist()
+ {static} Mode getDefaultMode()
+ {static} Patient getDefaultPatient()
}

class com.ronelgazar.touchtunes.adapter.SongsAdapter {
- Context context
- List<Song> songs
- MediaPlayer mediaPlayer
+ int getCount()
+ Object getItem(int)
+ long getItemId(int)
+ View getView(int,View,ViewGroup)
+ void notifyDataSetChanged()
}


class com.ronelgazar.touchtunes.model.Playlist {
- List<Song> playList
- {static} String PREFS_NAME
- {static} String PLAYLIST_KEY
+ {static} Creator<Playlist> CREATOR
+ int describeContents()
+ void writeToParcel(Parcel,int)
+ List<Song> getPlayList()
+ void setPlayList(List<Song>)
+ void addSong(Song)
+ void removeSong(Song)
+ void clearPlaylist()
+ Song getSong(int)
+ int getPlaylistSize()
+ void setSong(int,Song)
+ Song findSong(String)
+ String skipSong(Song)
+ String prevSong()
+ void printPlaylist()
+ InputStream getStreamFromUrl(String)
+ void savePlaylistToSharedPrefs(Context)
+ InputStream decodeSongData(Context,int)
}


class com.ronelgazar.touchtunes.ExampleInstrumentedTest {
+ void useAppContext()
}

class com.ronelgazar.touchtunes.activity.MainActivity {
- Toolbar toolbar
- ImageButton playButton
- Patient patient
- MediaPlayer buttonSoundPlayer
- BroadcastReceiver flashScreenReceiver
- Song currentSong
- NavigationView navigationView
- DrawerLayout drawerLayout
- FragmentManager fragmentManager
- boolean isReceiverRegistered
- BroadcastReceiver patientDataReceiver
# void onResume()
# void onPause()
# void onCreate(Bundle)
- void resetInteractionTimer()
# void onDestroy()
}


class com.ronelgazar.touchtunes.ExampleUnitTest {
+ void addition_isCorrect()
}

class com.ronelgazar.touchtunes.model.Song {
- String title
- String url
- MediaPlayer mediaPlayer
+ {static} Creator<Song> CREATOR
+ int describeContents()
+ void writeToParcel(Parcel,int)
+ String getTitle()
+ void setTitle(String)
+ String getUrl()
+ void setUrl(String)
+ MediaPlayer getMediaPlayer()
+ void setMediaPlayer(MediaPlayer)
+ void playSong()
+ void stopSong()
+ void pauseSong()
+ void resumeSong()
+ void printSong()
}


class com.ronelgazar.touchtunes.model.Therapist {
- String name
+ String getName()
+ void setName(String)
}


class com.ronelgazar.touchtunes.util.StreamSongTask {
# Void doInBackground(Song)
}

class com.ronelgazar.touchtunes.services.FirebaseService {
- {static} String TAG
- {static} String PATIENTS_COLLECTION
- {static} FirebaseFirestore db
- {static} FirebaseFirestoreSettings settings
- DataCallback callback
+ void onCreate()
- void initializeFirestore()
+ IBinder onBind(Intent)
+ {static} T getParcelableCompat(Bundle,String,Class<T>)
+ void getPatient(String,DataCallback)
+ void createPatient(Patient)
+ void updatePatient(Patient)
- void getDocRefData(DocumentReference)
+ void getDocRefData(DocumentReference,DataCallback)
}


interface com.ronelgazar.touchtunes.services.FirebaseService$DataCallback {
~ void onCallback(Map<String,Object>)
}

class com.ronelgazar.touchtunes.services.FirebaseService$LocalBinder {
+ FirebaseService getService()
}

class com.ronelgazar.touchtunes.model.Patient {
- String uid
- boolean isActive
- Mode mode
- String name
- Playlist playlist
+ {static} Creator<Patient> CREATOR
- void loadMode(DocumentReference)
- void loadPlaylist(DocumentReference)
+ void save()
+ int describeContents()
+ void writeToParcel(Parcel,int)
+ String getUid()
+ void setUid(String)
+ boolean isActive()
+ void setActive(boolean)
+ Mode getMode()
+ void setMode(Mode)
+ String getName()
+ void setName(String)
+ Playlist getPlaylist()
+ void setPlaylist(Playlist)
}


interface com.ronelgazar.touchtunes.model.Patient$PatientCallback {
~ void onPatientDataLoaded(Patient)
}

class com.ronelgazar.touchtunes.fragment.SettingsFragment {
- {static} Mode mode
+ void onCreatePreferences(Bundle,String)
- void bindPreferences()
- void updatePreferenceSummary(Preference,String)
+ {static} Mode updateSettings()
+ void onStop()
}


class com.ronelgazar.touchtunes.model.Mode {
- String name
- Map<String,Object> settings
- DocumentReference documentReference
+ {static} Creator<Mode> CREATOR
+ int describeContents()
+ void writeToParcel(Parcel,int)
- Parcelable getObjectAsParcelable(Object)
+ String getName()
+ void setName(String)
+ Map<String,Object> getSettings()
+ void setSettings(Map<String,Object>)
+ String getInteractionDuration()
+ void setInteractionDuration(String)
+ String getInteractionType()
+ void setInteractionType(String)
+ String getSessionDuration()
+ void setSessionDuration(String)
+ boolean getSoundInteraction()
+ void setSoundInteraction(boolean)
+ String getVibrationIntensity()
+ void setVibrationIntensity(String)
+ String getSessionDurationInMinutes()
+ void printMode()
+ void setSharedPreference(SharedPreferences)
}


class com.ronelgazar.touchtunes.services.BackgroundService {
- {static} int SESSION_TIMER_ID
- {static} int INTERACTION_TIMER_ID
- {static} int FLASH_COUNT
- {static} long[] VIBRATION_PATTERN
- Vibrator vibrator
- WindowManager.LayoutParams params
- Handler handler
- Random random
- CountDownTimer sessionTimer
- CountDownTimer interactionTimer
- boolean isPlaying
- MediaPlayer mediaPlayer
+ void onCreate()
+ int onStartCommand(Intent,int,int)
- void flashScreen(Context)
- void startSessionTimer(Patient)
- void startInteractionTimer(Patient)
- void resetInteractionTimer()
- void showToast(String)
+ void onDestroy()
+ IBinder onBind(Intent)
- void cancelTimers()
}




androidx.appcompat.app.AppCompatActivity <|-- com.ronelgazar.touchtunes.activity.LoginActivity
com.ronelgazar.touchtunes.activity.LoginActivity +.. com.ronelgazar.touchtunes.activity.LoginActivity$PatientCallback
android.widget.BaseAdapter <|-- com.ronelgazar.touchtunes.adapter.SongsAdapter
android.os.Parcelable <|.. com.ronelgazar.touchtunes.model.Playlist
androidx.appcompat.app.AppCompatActivity <|-- com.ronelgazar.touchtunes.activity.MainActivity
android.os.Parcelable <|.. com.ronelgazar.touchtunes.model.Song
android.os.AsyncTask <|-- com.ronelgazar.touchtunes.util.StreamSongTask
android.app.Service <|-- com.ronelgazar.touchtunes.services.FirebaseService
com.ronelgazar.touchtunes.services.FirebaseService +.. com.ronelgazar.touchtunes.services.FirebaseService$DataCallback
com.ronelgazar.touchtunes.services.FirebaseService +.. com.ronelgazar.touchtunes.services.FirebaseService$LocalBinder
com.ronelgazar.touchtunes.services.Binder <|-- com.ronelgazar.touchtunes.services.FirebaseService$LocalBinder
android.os.Parcelable <|.. com.ronelgazar.touchtunes.model.Patient
com.ronelgazar.touchtunes.model.Patient +.. com.ronelgazar.touchtunes.model.Patient$PatientCallback
androidx.preference.PreferenceFragmentCompat <|-- com.ronelgazar.touchtunes.fragment.SettingsFragment
android.os.Parcelable <|.. com.ronelgazar.touchtunes.model.Mode
android.app.Service <|-- com.ronelgazar.touchtunes.services.BackgroundService
@enduml